add '--no-check' option to configure scripts

diff --git a/gnome/configure b/gnome/configure
--- a/gnome/configure
+++ b/gnome/configure
@@ -5,9 +5,11 @@ if [ -e Makefile ]; then
 fi
 
 #check GNOME
-if [ -z `which gnome-session` ]; then
-	echo "ERROR: Can't find GNOME !"
-	exit 1
+if [ $1. != "--no-check" ]; then
+	if [ -z `which gnome-session` ]; then
+		echo "ERROR: Can't find GNOME !"
+		exit 1
+	fi
 fi
 
 cp Makefile.template Makefile
diff --git a/kde4/configure b/kde4/configure
--- a/kde4/configure
+++ b/kde4/configure
@@ -1,10 +1,12 @@
 #!/bin/bash
 
 #check KDE4
-if [ $kde4 = "--kde4" ]; then
-	if [ -z `which kdeinit4` ]; then
-		echo "ERROR: Can't find KDE4 !"
-		exit 1
+if [ $1. != "--no-check" ]; then
+	if [ $kde4 = "--kde4" ]; then
+		if [ -z `which kdeinit4` ]; then
+			echo "ERROR: Can't find KDE4 !"
+			exit 1
+		fi
 	fi
 fi
 
